### ISSUE TITLE
Questions on Implementation - Post Processing Script Example

### ISSUE THREAD

**Issue by macdadyj** [castelao/iridiumSBD#1]
* Iridium Short Burst Data version:
* Python version: 3.8
* Operating System: Ubuntu

### Description

- Do you have additional resources you'd be willing to share, i.e. types of data files you send, or post processing scripts you use?

**Comment by castelao** [comment]
I'm sorry for the delay. The idea of using a post processing script is to give as much freedom as you would have running commands in a shell. As an example, consider that you want to move the files to an archiving directory:


```
#!/bin/bash

# Script to consume ISBD messages received by DirectIP.

ARCHIVEDIR=/data/iridium/archive

target=$1

# exit if missing the target.
if [ -z "$target" ]
then
    echo "process_isbd_messages.sh requires a target. For example:"
    echo "process_isbd_messages.sh /data/my_file.isbd"
    exit
    exit 128
fi

echo `date` " - post-processing:" $target

mv $target $ARCHIVEDIR/$target
```

The server calls the post processing script with the name of the file where it saved the message as the first argument. Note the variable `target` capturing the value of `$1`.

A more realistic script would actually make something with this data. For instance, you could call a parser to decode the binary message and inject the obtained values into a database or send it to a message broker.
