### ISSUE TITLE
Questions on Implementation  - Initiating Mobile Terminated (MT) transmission

### ISSUE THREAD

**Issue by macdadyj** [castelao/iridiumSBD#2]
* Iridium Short Burst Data version:
* Python version: 3.8
* Operating System: Ubuntu

### Description

- Is there a way to initiate a message being sent (MO or MT) without having received a message? 
- Can you provide an example snippet of code or reference a place in your project for direction on the matter?

**Comment by castelao** [comment]
Yes, you can initiate a MO or MT without having received a message. If you're not using the acknowledged resource, each message is actually independent. In that sense the MO or MT only defines which direction the message is flowing, Mobile Originated or Mobile Terminated. It is up to you to keep track of the ids to connect the chain of communication.

Imagine a scenario that you send a message from your base station (MT) which will trigger your remote station to a series of procedures that will generate a sequence of messages. Each message is limited by ~2K, so it might be necessary to split in several messages. What we do with the messages on each end is up to us. The ISBD protocol only delivers the payload.
